<a href="https://colab.research.google.com/github/Martin26H/Manipulacion-y-Transformacion-de-Datos-con-Pandas-y-NumPy/blob/master/Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
dicct = {'Col1':[1,2,3,np.nan],
'Col2':[4, np.nan,6,7],
'Col3':['a','b','c', None]}

In [4]:
df = pd.DataFrame(dicct)

In [5]:
df

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [6]:
df.isnull()

    Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [7]:
df.isnull() * 1

   Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [9]:
df.fillna('Missing')

      Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [10]:
df.interpolate()

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [11]:
df.dropna()

   Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c